version: '3'
services:
  anki-sync-server:
    container_name: anki-sync-server
    hostname: anki-sync-server
    image: ghcr.io/kolbyml/anki-syncserver:latest
    environment:
      - MAX_SYNC_PAYLOAD_MEGS=50000
      - SYNC_USER1=${SYNC_USER1?anki-sync-server Requires a username and password in "SYNC_USER1=user:pass" format}
    ports:
      - "${SYNC_PORT:-8080}:8080"
    volumes: 
      - ${HOME}/.syncserver:${HOME}/.syncserver
    env_file:
      - .env
    restart: always
